### ISSUE TITLE
[1.12.2] Can't load the game -> crash

### ISSUE THREAD

**Issue by TheSnowyChickens** [LXGaming/Sledgehammer#10]
Hello,
after updating to the newest version, I can't start MC anymore.
(I used the main file from Curse, the second file from your additional files worked)

crash with SH v2.0.0-> https://paste.dimdev.org/iqoyihedax.mccrash

Forge: 2847

**Comment by BugmanBugman** [comment]
same thing is happening with me

**Comment by LXGaming** [comment]
What modpack are you running? and could provided the `debug.log`.

You may have to use Sledgehammer-1.12.2-**0.7**-2.0.0.jar (Available on GitHub and CurseForge) as other mods may not have been updated for Mixin 0.8

**Comment by TheSnowyChickens** [comment]
I play this modpack: https://www.curseforge.com/minecraft/modpacks/servo/files/2869978
0.7 is fine and work. I have to wait for more updates. 

Ty for this info. :)

**Comment by LXGaming** [comment]
VanillaFix doesn't support Mixin 0.8, The IllegalAccessError is caused by VanillaFix trying to access a method that no longer exists via reflection [MixinLoader.java#L56-L58](https://github.com/DimensionalDevelopment/VanillaFix/blob/a2b09002d92d54139daa7a1169dd8e1e792da05d/src/main/java/org/dimdev/vanillafix/modsupport/mixins/MixinLoader.java#L56-L58)

For now you will have to use the Mixin 0.7 version of Sledgehammer.

**Comment by TheSnowyChickens** [comment]
Okay, I take a look in the VanillaFix Github, if someone already reported this.
