### ISSUE TITLE
Sledgehammer conflicted by/with Portal Gun Fixer

### ISSUE THREAD

**Issue by Rongmario** [LXGaming/Sledgehammer#4]
Tried the mod out again, but: https://pastebin.com/0rECQa3v

**Comment by LXGaming** [comment]
Doing a quick search I can see that two version of Sledgehammer have been loaded
```
  Sledgehammer-1.12.2-1.4.2.jar
  Sledgehammer-1.12.2-1.4.7
```

Can you please re-test after removing v1.4.2

**Comment by Rongmario** [comment]
That wasn't tagged as .jar, but .0, and still got the same error: (debug.log): https://pastebin.com/VwJVHsnR

**Comment by LXGaming** [comment]
Is there a download available for this modpack?

**Comment by Rongmario** [comment]
It's custom right now, sorry. I guess I'll try different combination of mods to see which is the one conflicting.

**Comment by LXGaming** [comment]
I went though your log and downloaded any mods which loaded a CoreMod.

I've tracked down the issue to a conflict with Portal Gun Fixer and Sledgehammer

**Comment by Rongmario** [comment]
Alright, I'll crosspost this issue over to KitsuneAlex.

**Comment by LXGaming** [comment]
Please re-test with https://github.com/LXGaming/Sledgehammer/releases/tag/v1.4.8

This issue is caused by PGF initializing Mixin in the static constructor of their CoreMod, Mixin registers Tweakers which get loading by LaunchWrapper before Forge continues loading CoreMods which results in Sledgehammers CoreMod getting loaded too late.

~The fix I've implemented changed the TweakClass defined in the MAINFEST to point to SledgehammerTweaker which allows Sledgehammer to load early regardless of any CoreMods which initialize Mixin.~

~This does result in `Sledgehammer-1.12.2-1.4.8.jar` being incompatible with SpongeVanilla but `Sledgehammer-1.12.2-1.4.8-sponge.jar` will still be compatible.~

Also the SortingIndex of the SledgehammerLoadingPlugin has been set to the lowest possible value as it's now setup to bootstrap the SledgehammerTweaker if it has not already been loaded.

**Comment by Rongmario** [comment]
Sounds good to me.

It loads :)

**Comment by LXGaming** [comment]
After looking into #5 I discovered that changing the TweakClass in the manifest actually prevents Mixin from automatically loading the MixinConfigs defined in the manifest, As a result the changes I previously made have been reverted in v1.5.0, Sledgehammer will continue to load but Mixins targeting mods will be unavailable.

Upon further testing I discovered that due to how PGF is loading Mixin it is currently incompatible with the latest releases of SpongeForge due to certain Forge classes getting loading far too early.

PGF will need to fix this on there end.
