### ISSUE TITLE
Enabling "premature-culling" crashes with CodeChickenLib

### ISSUE THREAD

**Issue by MasterEnderman** [LXGaming/Sledgehammer#40]
Sledgehammer version: 2.0.23

The crash report mentions `java.lang.NoClassDefFoundError: net/minecraft/client/renderer/RenderGlobal`

I noticed that Sledgehammer overrides this method here: https://github.com/LXGaming/Sledgehammer/blob/1.12.2/src/main/java/io/github/lxgaming/sledgehammer/mixin/core/client/renderer/RenderGlobalMixin.java

Here is the error I found in the log file: https://gist.github.com/MasterEnderman/bc32e71a7cf4685b417a401afd196796

If you disable the "premature-culling" feature, it prevents the game from crashing.

**Comment by LXGaming** [comment]
Please provide your `debug.log` file, I suspect there is a conflict with another mod.

**Comment by MasterEnderman** [comment]
Recreated the issue and let it crash again.
Here's the [debug.log](https://gist.github.com/MasterEnderman/f47921b45b5a9aa3c66627f7e1ce9731)

**Comment by LXGaming** [comment]
Thank you for the `debug.log`, I was able to identify several mods which are patching `RenderGlobal` in various ways.

There is a conflict between Sledgehammer and LoliASM (CensoredASM), both mods are attempting to fix the same issue but LoliASM is getting to it first which results in the Sledgehammer patch failing.

Don't see any reason to fix this issue, you don't need two different mods patching the same issue, at that point one of the mods / patches is redundant.

The fix for this is to disable the patch in one of the mods, It's one of the reasons why all of Sledgehammers patches are configurable.
- Sledgehammer: `premature-culling=false`
- LoliASM: `fixMC88176=false`

Thank you for reporting this issue, I'll look into creating a list of mod incompatibilities so in future this issue is documented for other users.
