### ISSUE TITLE
1.12.2 Crashes on worldgen with FutureMC

### ISSUE THREAD

**Issue by toErIpNid** [LXGaming/Sledgehammer#50]
Crash Log: https://mclo.gs/HQ0wEYc

Let me know if you need any more info.

**Comment by LXGaming** [comment]
Please provide the `debug.log` file

**Comment by toErIpNid** [comment]
[latest.log](https://github.com/LXGaming/Sledgehammer/files/14190528/latest.log)
Do you mean this log file? I couldn't find anything with debug.log in its name.

**Comment by LXGaming** [comment]
Is this a modpack that I can download so I can try and reproduce the issue? I don't have any issues when running just FutureMC and Sledgehammer.

Looking at the `latest.log` I'm seeing Notch obfuscation which indicates that the game isn't being deobfuscated.

**Comment by toErIpNid** [comment]
Yeah, I can give you the export. Whenever Sledgehammer is in the pack weird shit in general happens, like it not crashing but instead having sound cutting out completely. I'm using ATLauncher in case it matters.
[Dungeonpunk 1.12.2.zip](https://github.com/LXGaming/Sledgehammer/files/14205275/Dungeonpunk.1.12.2.zip)

**Comment by LXGaming** [comment]
Thanks for the export. So the issue has changed? We've gone from the game crashing to now it's launching fine? Can you provide your `latest.log` when the "weird shit" happens.

I imported it into PrismLauncher then add Sledgehammer to the pack and everything seems to be fine?

**Comment by toErIpNid** [comment]
My bad, Sledgehammer was not included in the export. You need to try with it installed and see if anything weird happens. I'll grab a log from my end in the meantime.

**Comment by toErIpNid** [comment]
[latest.log](https://github.com/LXGaming/Sledgehammer/files/14213750/latest.log)
Well fantastic now it's not doing it anymore?

**Comment by LXGaming** [comment]
Yeah I made sure Sledgehammer was present when I was testing the pack, I didn't notice any issues.

The key difference that I can see when comparing the two `latest.log` files is this line:
`A re-entrant transformer 'net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer' was detected and will no longer process meta class data`
This explains why Notch mappings are present in the first `latest.log` as the deobfuscation was stopped.

If you're no longer having issues then there is unfortunately not much I can do. If you encounter the issue again I would appreciate it if you could create a fresh export and then test that export by importing it as a fresh instance and check that the issue is still present, if you can reliably reproduce the issue then hopefully I'll be able to as well and then I can debug the issue.

**Comment by LXGaming** [comment]
If you encounter this issue again and can create a modpack export where the issue can be reproduced then feel free to reply / reopen this issue.
